#pragma once

/* Generated with cbindgen:0.29.2 */

/* Auto-generated by cbindgen from sbpf-runtime. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct ExecContext ExecContext;

typedef struct SbpfContext {
  void *exec_ctx;
  uint64_t mm_program_start;
  uint64_t mm_program_end;
  uint64_t mm_stack_start;
  uint64_t mm_stack_end;
  uint64_t mm_heap_start;
  uint64_t mm_heap_end;
  uint64_t mm_input_start;
  uint64_t mm_input_end;
  uint64_t heap_pos;
  uint8_t program_id[32];
  uint64_t token_source_amount;
  uint64_t token_dest_amount;
  uint64_t token2022_source_amount;
  uint64_t token2022_dest_amount;
  uint64_t rust_source_amount;
  uint64_t rust_dest_amount;
  uint64_t instruction_counter;
  uint64_t instruction_limit;
  uint64_t compute_units;
} SbpfContext;

typedef struct SolBytes {
  const uint8_t *val;
  uint64_t val_len;
} SolBytes;

/**
 * C ABI shape for setting RuntimeConfig through an opaque exec_ctx pointer.
 */
typedef struct RuntimeConfigFFI {
  uint64_t clock_slot;
  int64_t clock_epoch_start_timestamp;
  uint64_t clock_epoch;
  uint64_t clock_leader_schedule_epoch;
  int64_t clock_unix_timestamp;
  uint64_t rent_lamports_per_byte_year;
  double rent_exemption_threshold;
  uint8_t rent_burn_percent;
  uint64_t epoch_schedule_slots_per_epoch;
  uint64_t epoch_schedule_leader_schedule_slot_offset;
  uint8_t epoch_schedule_warmup;
  uint64_t epoch_schedule_first_normal_epoch;
  uint64_t epoch_schedule_first_normal_slot;
  uint64_t stack_height;
  uint64_t remaining_compute_units;
} RuntimeConfigFFI;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

uint64_t sbpf_call(const struct SbpfContext *ctx, SbpfProgramFn program_fn);

/**
 * Handle VM address translation failure
 */
void sbpf_access_violation(void);

/**
 * Debug print for untranslated VM addresses
 */
void sbpf_vm_to_host_debug(uint64_t vm_addr);

void *sbpf_vm_to_host_or_identity(const struct SbpfContext *ctx, uint64_t vm_addr);

void sbpf_trace_callx(uint64_t target_addr, uint64_t byte_offset, uint64_t call_site_pc);

void sbpf_indirect_call(const struct SbpfContext *ctx, uint64_t target_addr, uint64_t call_site_pc);

/**
 * Check host memory access bounds for lifted load/store instructions.
 * Returns the original address if in-bounds, otherwise aborts with AccessViolation.
 */
uint64_t sbpf_check_host_memory_access(const struct SbpfContext *ctx,
                                       uint64_t addr,
                                       uint64_t len,
                                       uint64_t pc);

void abort_(void);

void sbpf_set_instruction_limit(const struct SbpfContext *ctx, uint64_t limit);

void sbpf_reset_instruction_counter(const struct SbpfContext *ctx);

void sbpf_instruction_tick(const struct SbpfContext *ctx);

void sol_panic_(const uint8_t *file, uint64_t len, uint64_t line, uint64_t col);

uint64_t sol_invoke_signed_c(const struct SbpfContext *ctx,
                             const uint8_t *instruction,
                             const uint8_t *account_infos,
                             uint64_t account_infos_len,
                             const uint8_t *_signers_seeds,
                             uint64_t _signers_seeds_len);

uint64_t sol_invoke_signed_rust(const struct SbpfContext *ctx,
                                const uint8_t *instruction,
                                const uint8_t *account_infos,
                                uint64_t account_infos_len,
                                const uint8_t *_signers_seeds,
                                uint64_t _signers_seeds_len);

void sol_set_return_data(const struct SbpfContext *ctx, const uint8_t *data, uint64_t len);

uint64_t sol_get_return_data(const struct SbpfContext *ctx,
                             uint8_t *data,
                             uint64_t len,
                             uint8_t *program_id);

uint64_t sol_sha256(const struct SolBytes *vals, uint64_t cnt, uint8_t *hash);

uint64_t sol_keccak256(const struct SolBytes *vals, uint64_t cnt, uint8_t *hash);

uint64_t sol_blake3(const struct SolBytes *vals, uint64_t cnt, uint8_t *hash);

uint64_t sol_secp256k1_recover(const uint8_t *hash,
                               uint64_t recovery_id,
                               const uint8_t *signature,
                               uint8_t *result);

uint64_t sol_poseidon(uint64_t params,
                      const uint8_t *endianness,
                      const uint8_t *vals,
                      uint64_t vals_len,
                      uint8_t *result);

uint64_t sol_curve_validate_point(uint64_t curve_id, const uint8_t *point, uint8_t *_result);

uint64_t sol_curve_group_op(uint64_t curve_id,
                            uint64_t op,
                            const uint8_t *left,
                            const uint8_t *right,
                            uint8_t *result);

uint64_t sol_curve_multiscalar_mul(uint64_t curve_id,
                                   const uint8_t *scalars,
                                   const uint8_t *points,
                                   uint64_t num,
                                   uint8_t *result);

uint64_t sol_curve_pairing_map(uint64_t _curve_id,
                               const uint8_t *_point,
                               uint64_t _num,
                               uint8_t *_result);

uint64_t sol_curve_decompress(uint64_t curve_id, const uint8_t *point, uint8_t *result);

uint64_t sol_alt_bn128_group_op(uint64_t op,
                                const uint8_t *input,
                                uint64_t input_len,
                                uint8_t *result,
                                uint64_t result_len);

uint64_t sol_alt_bn128_compression(uint64_t op,
                                   const uint8_t *input,
                                   uint64_t input_len,
                                   uint8_t *result,
                                   uint64_t result_len);

uint64_t sol_big_mod_exp(const uint8_t *params, uint64_t params_len, uint8_t *result);

uint64_t syscall_dispatch(const struct SbpfContext *ctx,
                          uint64_t hash,
                          uint64_t r1,
                          uint64_t r2,
                          uint64_t r3,
                          uint64_t r4,
                          uint64_t r5);

/**
 * Create a new execution context. Caller must free with `sbpf_exec_ctx_free`.
 *
 * `config_json` is an optional JSON string (may be null) containing runtime
 * configuration fields like `clockUnixTimestamp`. When provided, the context's
 * `RuntimeConfig` is updated accordingly.
 */
struct ExecContext *sbpf_exec_ctx_new(uint64_t compute_units, const char *config_json);

/**
 * Free an execution context previously created by `sbpf_exec_ctx_new`.
 */
void sbpf_exec_ctx_free(struct ExecContext *ctx);

/**
 * Returns the number of log entries collected during execution.
 */
uint64_t sbpf_exec_ctx_log_count(const struct ExecContext *ctx);

/**
 * Returns the byte length of the log entry at `index`.
 */
uint64_t sbpf_exec_ctx_get_log_len(const struct ExecContext *ctx, uint64_t index);

/**
 * Copy log entry at `index` into `buf`. Returns number of bytes copied.
 */
uint64_t sbpf_exec_ctx_get_log(const struct ExecContext *ctx,
                               uint64_t index,
                               uint8_t *buf,
                               uint64_t buf_len);

/**
 * Returns the byte length of return data.
 */
uint64_t sbpf_exec_ctx_return_data_len(const struct ExecContext *ctx);

/**
 * Copy return data into `buf` and program_id into `program_id_out`.
 * Returns the total return data length (may exceed `buf_len`).
 */
uint64_t sbpf_exec_ctx_get_return_data(const struct ExecContext *ctx,
                                       uint8_t *buf,
                                       uint64_t buf_len,
                                       uint8_t *program_id_out);

/**
 * Returns the compute units value stored in the context.
 */
uint64_t sbpf_exec_ctx_get_compute_units(const struct ExecContext *ctx);

/**
 * Copy the configured program id into `out32` (32 bytes).
 * Returns bytes copied (32) on success, 0 on error.
 */
uint64_t sbpf_exec_ctx_get_program_id(const struct ExecContext *ctx, uint8_t *out32);

/**
 * Build Solana input buffer from JSON file or directory.
 *
 * # Arguments
 * * `accounts_path` - C string containing JSON file or directory path (null = no accounts)
 * * `buffer_len` - Output parameter for the actual buffer length
 *
 * # Returns
 * Heap-allocated buffer pointer (null on error, error written to stderr).
 * Caller must free using `sbpf_free_input_buffer()`.
 *
 * # Safety
 * - `accounts_path` must be null or a valid null-terminated C string
 * - `buffer_len` must be a valid pointer to u64
 */
uint8_t *sbpf_build_input_buffer(const char *accounts_path, uint64_t *buffer_len);

/**
 * Free a buffer allocated by `sbpf_build_input_buffer`.
 *
 * # Safety
 * - `ptr` must be null or a pointer previously returned by `sbpf_build_input_buffer`
 * - `len` must match the length returned from `sbpf_build_input_buffer`
 * - Must not be called more than once on the same pointer
 */
void sbpf_free_input_buffer(uint8_t *ptr, uint64_t len);

void sol_log_(const struct SbpfContext *ctx, const uint8_t *msg, uint64_t len);

void sol_log_64_(const struct SbpfContext *ctx,
                 uint64_t a,
                 uint64_t b,
                 uint64_t c,
                 uint64_t d,
                 uint64_t e);

void sol_log_compute_units_(const struct SbpfContext *ctx);

void sol_log_pubkey(const struct SbpfContext *ctx, const uint8_t *pubkey);

void sol_log_data(const struct SbpfContext *ctx, const struct SolBytes *data, uint64_t data_len);

uint64_t bpf_trace_printf(const struct SbpfContext *ctx,
                          const uint8_t *fmt,
                          uint64_t fmt_len,
                          uint64_t r3,
                          uint64_t r4,
                          uint64_t r5);

void log_64(const struct SbpfContext *ctx,
            uint64_t a,
            uint64_t b,
            uint64_t c,
            uint64_t d,
            uint64_t e);

void sol_memcpy_(uint8_t *dst, const uint8_t *src, uint64_t n);

void sol_memmove_(uint8_t *dst, const uint8_t *src, uint64_t n);

uint64_t sol_memcmp_(const uint8_t *s1, const uint8_t *s2, uint64_t n, int32_t *result);

void sol_memset_(uint8_t *dst, uint64_t c, uint64_t n);

/**
 * Bump allocator matching Solana's BpfAllocator.
 *
 * Reads/writes `SbpfContext.heap_pos` (index 9) for allocation state.
 * When `SBPF_INLINE_ALLOC` is enabled at compile time, this function is
 * replaced by IR-level inlining and never called. This serves as the
 * fallback path for `SBPF_INLINE_ALLOC=OFF`.
 */
uint64_t sol_alloc_free_(const struct SbpfContext *ctx, uint64_t size, uint64_t free_addr);

uint64_t sol_create_program_address(const struct SolBytes *seeds,
                                    uint64_t seeds_len,
                                    const uint8_t *program_id,
                                    uint8_t *address_out);

uint64_t sol_try_find_program_address(const struct SolBytes *seeds,
                                      uint64_t seeds_len,
                                      const uint8_t *program_id,
                                      uint8_t *address_out,
                                      uint8_t *bump_seed_out);

uint64_t bpf_gather_bytes(uint64_t arg1,
                          uint64_t arg2,
                          uint64_t arg3,
                          uint64_t arg4,
                          uint64_t arg5);

uint64_t bpf_mem_frob(uint8_t *addr, uint64_t len, uint64_t _a3, uint64_t _a4, uint64_t _a5);

uint64_t bpf_str_cmp(const uint8_t *a, const uint8_t *b, uint64_t _a3, uint64_t _a4, uint64_t _a5);

uint64_t bpf_syscall_string(const struct SbpfContext *ctx,
                            const uint8_t *msg,
                            uint64_t len,
                            uint64_t _a3,
                            uint64_t _a4,
                            uint64_t _a5);

uint64_t bpf_syscall_u64(uint64_t arg1, uint64_t arg2, uint64_t arg3, uint64_t arg4, uint64_t arg5);

uint64_t bpf_syscall_noop(uint64_t _a1, uint64_t _a2, uint64_t _a3, uint64_t _a4, uint64_t _a5);

uint64_t bpf_garbage(uint64_t _a1, uint64_t _a2, uint64_t _a3, uint64_t _a4, uint64_t _a5);

uint64_t bpf_rand(uint64_t _a1, uint64_t _a2, uint64_t _a3, uint64_t _a4, uint64_t _a5);

uint64_t sbpf_exec_ctx_set_runtime_config(void *exec_ctx, const struct RuntimeConfigFFI *config);

uint64_t sbpf_exec_ctx_reset_runtime_config(void *exec_ctx);

uint64_t sol_get_processed_sibling_instruction(uint64_t _index,
                                               uint8_t *_meta,
                                               uint8_t *_program_id,
                                               uint8_t *_data,
                                               uint8_t *_accounts);

uint64_t sol_get_stack_height(const struct SbpfContext *ctx);

uint64_t sol_remaining_compute_units(const struct SbpfContext *ctx);

uint64_t sol_get_epoch_rewards_sysvar(uint8_t *_out);

uint64_t sol_get_last_restart_slot(uint8_t *out);

uint64_t sol_get_clock_sysvar(const struct SbpfContext *ctx, uint8_t *out);

uint64_t sol_get_epoch_schedule_sysvar(const struct SbpfContext *ctx, uint8_t *out);

uint64_t sol_get_fees_sysvar(uint8_t *out);

uint64_t sol_get_rent_sysvar(const struct SbpfContext *ctx, uint8_t *out);

uint64_t sol_get_sysvar(const struct SbpfContext *ctx,
                        const uint8_t *sysvar_id,
                        uint8_t *out,
                        uint64_t offset,
                        uint64_t length);

uint64_t sol_get_epoch_stake(const uint8_t *_vote_addr, uint64_t _vote_addr_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus
